name: 'kara_dbt'
version: '1.0'
config-version: 2

profile: 'kara_dbt'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  kara_dbt:
    +materialized: view

