version: 2

models:
  - name: stg_telegram_messages
    description: "Staging model that standardizes raw Telegram messages for analysis"
    columns:
      - name: message_id
        description: "Unique identifier of the message"
        tests:
          - unique
          - not_null

      - name: channel
        description: "Name of the Telegram channel"

      - name: message_date
        description: "Timestamp when the message was sent"
        tests:
          - not_null

      - name: message
        description: "Raw text content of the message"

      - name: media_url
        description: "Path or URL to the media file if available"

      - name: has_image
        description: "TRUE if media is an image, else FALSE"
        
version: 2

models:
  - name: stg_detected_objects
    description: "YOLO object detection results from Telegram media"
    columns:
      - name: message_id
        description: "ID of the message with the image"
        tests:
          - not_null

      - name: object_label
        description: "Object class label (e.g. scissors, remote)"
        tests:
          - not_null

      - name: confidence
        description: "Model confidence score"

      - name: bounding_box
        description: "Object bounding box in JSON format"

      - name: media_path
        description: "Local path to the image file"
